//
// ###
// Ryx — Lookup System
// ###
//
// A "lookup" is the suffix after `__` in a filter expression.
// Examples:
//   `age__gte=25`           → lookup = "gte",  SQL = "age >= $1"
//   `name__icontains="bob"` → lookup = "icontains", SQL = "LOWER(name) LIKE LOWER($1)"
//   `id__in=[1,2,3]`        → lookup = "in",   SQL = "id IN ($1, $2, $3)"
//
// # Extensibility design 
//
// Users can register custom lookups from Python:
//
//   from Ryx import register_lookup
//
//   @register_lookup("uuid_prefix")
//   def uuid_prefix_lookup(field: str, _value) -> str:
//       return f"{field}::text LIKE ${{placeholder}}"
//
// Internally this works via a global `DashMap<String, LookupFn>` that stores
// both the built-in lookups and any user-registered ones. We use DashMap
// (concurrent HashMap) so registrations from Python threads are safe.
//
// Why not a trait object (`Box<dyn Fn>`)? We need lookups to be thread-safe
// and Send+Sync since they're shared across async tasks. Function pointers
// (`fn`) are always Send+Sync, so they're stored directly in the map.
// For user-registered lookups (coming from Python callables) we store a
// Python-side callable name and call back to Python at query-build time.
//
// # SQL placeholder strategy 
//
// Different databases use different placeholder syntax:
//   PostgreSQL:  $1, $2, $3, ...
//   MySQL:       ?,  ?,  ?,  ...
//   SQLite:      ?,  ?,  ?,  ...
//
// We abstract this by always generating `?` placeholders in the AST and
// letting the backend-specific compiler rewrite them. This is exactly what
// sqlx's `AnyPool` does internally.
// ###

use std::collections::HashMap;
use std::sync::{OnceLock, RwLock};

use crate::errors::{RyxError, RyxResult};

// ###
// Core types
// ###

/// Context passed to every lookup function when building a SQL fragment.
///
/// The lookup function receives the column name and must return a SQL fragment
/// with `?` as the value placeholder. It does NOT need to know the placeholder
/// index — the compiler handles numbering.
///
/// # Example (for the "gte" lookup)
/// ```
/// // field = "age", returns: "age >= ?"
/// fn gte_lookup(ctx: &LookupContext) -> String {
///     format!("{} >= ?", ctx.column)
/// }
/// ```
#[derive(Debug, Clone)]
pub struct LookupContext {
    /// The SQL column name, already quoted/escaped.
    pub column: String,

    /// Whether the lookup is negated (i.e., inside an `exclude()` call).
    /// Most lookups ignore this — negation is applied by the compiler.
    pub negated: bool,
}

/// The function signature for a built-in lookup implementation.
///
/// Takes a `LookupContext` and returns a SQL fragment string.
/// The function must be `fn` (not closure) to be `Send + Sync`.
pub type LookupFn = fn(&LookupContext) -> String;

/// A lookup that was registered from Python: stores the callable and a
/// Rust-generated SQL template where `{col}` is the column placeholder.
///
/// Python-registered lookups are called at SQL-build time with the column
/// name substituted in. This avoids holding the GIL for every query.
/// The Python callable is only invoked once at registration time to extract
/// the SQL template string.
#[derive(Debug, Clone)]
pub struct PythonLookup {
    /// Pre-rendered SQL template. Example: `"LOWER({col}) LIKE LOWER(?)"`
    /// The caller substitutes `{col}` with the actual column name.
    pub sql_template: String,
}

// 
// Global lookup registry
// 
/// The two registries live side-by-side:
/// - `builtin`: populated once at startup with the built-in lookups
/// - `custom`:  populated at runtime with user-registered lookups
///
/// We check `custom` first so users can override built-ins (e.g., to change
/// the SQL generated by `icontains` for a database that has native ILIKE).
struct LookupRegistry {
    builtin: HashMap<&'static str, LookupFn>,
    custom: HashMap<String, PythonLookup>,
}

static REGISTRY: OnceLock<RwLock<LookupRegistry>> = OnceLock::new();

/// Initialize the registry with all built-in lookups.
/// Called once from `lib.rs` module initialization.
pub fn init_registry() {
    REGISTRY.get_or_init(|| {
        let mut builtin = HashMap::new();

        // Comparison lookups 
        builtin.insert("exact", exact as LookupFn);
        builtin.insert("gt", gt as LookupFn);
        builtin.insert("gte", gte as LookupFn);
        builtin.insert("lt", lt as LookupFn);
        builtin.insert("lte", lte as LookupFn);

        // String lookups
        builtin.insert("contains", contains as LookupFn);
        builtin.insert("icontains", icontains as LookupFn);
        builtin.insert("startswith", startswith as LookupFn);
        builtin.insert("istartswith", istartswith as LookupFn);
        builtin.insert("endswith", endswith as LookupFn);
        builtin.insert("iendswith", iendswith as LookupFn);

        // Null lookups 
        // `isnull` is special: it ignores the value entirely and produces
        // IS NULL / IS NOT NULL. The value passed (True/False) is read by
        // the compiler, not by this function.
        builtin.insert("isnull", isnull as LookupFn);

        // Membership lookups 
        // `in` is also special: the compiler expands it into
        // `col IN (?, ?, ?)` based on the number of values provided.
        builtin.insert("in", in_lookup as LookupFn);

        // Range lookup 
        builtin.insert("range", range as LookupFn);

        RwLock::new(LookupRegistry {
            builtin,
            custom: HashMap::new(),
        })
    });
}

// 
// Registry public API
// 
/// Register a custom lookup from Python.
///
/// # Arguments
/// * `name`         — the lookup name (e.g. `"uuid_prefix"`)
/// * `sql_template` — SQL fragment with `{col}` as column placeholder and
///                    `?` as value placeholder. Example: `"{col}::text LIKE ?"`
///
/// # Errors
/// Returns `RyxError::Internal` if the registry hasn't been initialized
/// (should never happen in practice since `init_registry()` runs at import).
pub fn register_custom(name: impl Into<String>, sql_template: impl Into<String>) -> RyxResult<()> {
    let registry = REGISTRY
        .get()
        .ok_or_else(|| RyxError::Internal("Lookup registry not initialized".into()))?;

    let mut guard = registry
        .write()
        .map_err(|e| RyxError::Internal(format!("Registry lock poisoned: {e}")))?;

    guard.custom.insert(
        name.into(),
        PythonLookup { sql_template: sql_template.into() },
    );

    Ok(())
}

/// Resolve a lookup name + column into a SQL fragment.
///
/// Resolution order: custom registry → built-in registry → error.
/// This lets users override built-ins selectively.
///
/// # Returns
/// A SQL fragment string with `?` as the value placeholder.
///
/// # Errors
/// [`RyxError::UnknownLookup`] if the name is not found in either registry.
pub fn resolve(field: &str, lookup_name: &str, ctx: &LookupContext) -> RyxResult<String> {
    let registry = REGISTRY
        .get()
        .ok_or_else(|| RyxError::Internal("Lookup registry not initialized".into()))?;

    let guard = registry
        .read()
        .map_err(|e| RyxError::Internal(format!("Registry lock poisoned: {e}")))?;

    // Check custom registry first (allows overriding built-ins)
    if let Some(custom) = guard.custom.get(lookup_name) {
        return Ok(custom.sql_template.replace("{col}", &ctx.column));
    }

    // Fall back to built-in lookup functions
    if let Some(lookup_fn) = guard.builtin.get(lookup_name) {
        return Ok(lookup_fn(ctx));
    }

    Err(RyxError::UnknownLookup {
        field: field.to_string(),
        lookup: lookup_name.to_string(),
    })
}

/// Returns the list of all registered lookup names (built-in + custom).
/// Used by the Python layer to provide helpful error messages and IDE
/// autocompletion support.
pub fn registered_lookups() -> RyxResult<Vec<String>> {
    let registry = REGISTRY
        .get()
        .ok_or_else(|| RyxError::Internal("Lookup registry not initialized".into()))?;

    let guard = registry
        .read()
        .map_err(|e| RyxError::Internal(format!("Registry lock poisoned: {e}")))?;

    let mut names: Vec<String> = guard
        .builtin
        .keys()
        .map(|k| k.to_string())
        .chain(guard.custom.keys().cloned())
        .collect();
    names.sort();
    Ok(names)
}

// ###
// Built-in lookup implementations
//
// Each function takes a `LookupContext` and returns a SQL fragment.
// Rules:
//   - Always use `?` as the value placeholder
//   - Never include the value itself (SQL injection prevention)
//   - Column name is already safely quoted by the query builder
// ###

/// `field__exact=value` → `field = ?`
///
/// This is also the *implicit* lookup: `filter(name="Alice")` is equivalent
/// to `filter(name__exact="Alice")`.
fn exact(ctx: &LookupContext) -> String {
    format!("{} = ?", ctx.column)
}

/// `field__gt=value` → `field > ?`
fn gt(ctx: &LookupContext) -> String {
    format!("{} > ?", ctx.column)
}

/// `field__gte=value` → `field >= ?`
fn gte(ctx: &LookupContext) -> String {
    format!("{} >= ?", ctx.column)
}

/// `field__lt=value` → `field < ?`
fn lt(ctx: &LookupContext) -> String {
    format!("{} < ?", ctx.column)
}

/// `field__lte=value` → `field <= ?`
fn lte(ctx: &LookupContext) -> String {
    format!("{} <= ?", ctx.column)
}

/// `field__contains="bob"` → `field LIKE ?`  (with `%value%` at bind time)
///
/// Case-sensitive substring match. The `%` wrapping is applied by the
/// executor when binding the value, not in the SQL fragment itself.
fn contains(ctx: &LookupContext) -> String {
    format!("{} LIKE ?", ctx.column)
}

/// `field__icontains="bob"` → `LOWER(field) LIKE LOWER(?)`
///
/// Case-insensitive substring match. Works on all backends without relying
/// on PostgreSQL-specific `ILIKE`. The `%value%` wrapping happens at bind time.
fn icontains(ctx: &LookupContext) -> String {
    format!("LOWER({}) LIKE LOWER(?)", ctx.column)
}

/// `field__startswith="pr"` → `field LIKE ?`  (with `value%` at bind time)
fn startswith(ctx: &LookupContext) -> String {
    format!("{} LIKE ?", ctx.column)
}

/// `field__istartswith="pr"` → `LOWER(field) LIKE LOWER(?)`
fn istartswith(ctx: &LookupContext) -> String {
    format!("LOWER({}) LIKE LOWER(?)", ctx.column)
}

/// `field__endswith="ing"` → `field LIKE ?`  (with `%value` at bind time)
fn endswith(ctx: &LookupContext) -> String {
    format!("{} LIKE ?", ctx.column)
}

/// `field__iendswith="ing"` → `LOWER(field) LIKE LOWER(?)`
fn iendswith(ctx: &LookupContext) -> String {
    format!("LOWER({}) LIKE LOWER(?)", ctx.column)
}

/// `field__isnull=True` → `field IS NULL`
/// `field__isnull=False` → `field IS NOT NULL`
///
/// Note: the True/False distinction is handled by the compiler which reads the
/// bound value. This function always returns the IS NULL form; the compiler
/// swaps to IS NOT NULL when the value is False/0.
fn isnull(ctx: &LookupContext) -> String {
    // The compiler reads the Python boolean and rewrites this.
    // We return the base form here.
    format!("{} IS NULL", ctx.column)
}

/// `field__in=[1, 2, 3]` → `field IN (?, ?, ?)`
///
/// Note: this returns a *template* — the compiler replaces `(?)` with
/// the correct number of placeholders based on the list length.
fn in_lookup(ctx: &LookupContext) -> String {
    // Single `?` — compiler expands to `(?, ?, ...)` based on value count
    format!("{} IN (?)", ctx.column)
}

/// `field__range=(low, high)` → `field BETWEEN ? AND ?`
///
/// Uses two bind parameters. The compiler handles this specially.
fn range(ctx: &LookupContext) -> String {
    format!("{} BETWEEN ? AND ?", ctx.column)
}