//
// ###
// Ryx — Lookup System
// ###
//
// A "lookup" is the suffix after `__` in a filter expression.
// Examples:
//   `age__gte=25`           → lookup = "gte",  SQL = "age >= $1"
//   `name__icontains="bob"` → lookup = "icontains", SQL = "LOWER(name) LIKE LOWER($1)"
//   `id__in=[1,2,3]`        → lookup = "in",   SQL = "id IN ($1, $2, $3)"
//
// # Extensibility design
//
// Users can register custom lookups from Python:
//
//   from Ryx import register_lookup
//
//   @register_lookup("uuid_prefix")
//   def uuid_prefix_lookup(field: str, _value) -> str:
//       return f"{field}::text LIKE ${{placeholder}}"
//
// Internally this works via a global `DashMap<String, LookupFn>` that stores
// both the built-in lookups and any user-registered ones. We use DashMap
// (concurrent HashMap) so registrations from Python threads are safe.
//
// Why not a trait object (`Box<dyn Fn>`)? We need lookups to be thread-safe
// and Send+Sync since they're shared across async tasks. Function pointers
// (`fn`) are always Send+Sync, so they're stored directly in the map.
// For user-registered lookups (coming from Python callables) we store a
// Python-side callable name and call back to Python at query-build time.
//
// # SQL placeholder strategy
//
// Different databases use different placeholder syntax:
//   PostgreSQL:  $1, $2, $3, ...
//   MySQL:       ?,  ?,  ?,  ...
//   SQLite:      ?,  ?,  ?,  ...
//
// We abstract this by always generating `?` placeholders in the AST and
// letting the backend-specific compiler rewrite them. This is exactly what
// sqlx's `AnyPool` does internally.
// ###

use std::collections::HashMap;
use std::sync::{OnceLock, RwLock};

use crate::errors::{RyxError, RyxResult};
use crate::pool::Backend;

// ###
// Core types
// ###

/// Context passed to every lookup function when building a SQL fragment.
///
/// The lookup function receives the column name and must return a SQL fragment
/// with `?` as the value placeholder. It does NOT need to know the placeholder
/// index — the compiler handles numbering.
///
/// # Example (for the "gte" lookup)
/// ```
/// // field = "age", returns: "age >= ?"
/// fn gte_lookup(ctx: &LookupContext) -> String {
///     format!("{} >= ?", ctx.column)
/// }
/// ```
#[derive(Debug, Clone)]
pub struct LookupContext {
    /// The SQL column name, already quoted/escaped.
    pub column: String,

    /// Whether the lookup is negated (i.e., inside an `exclude()` call).
    /// Most lookups ignore this — negation is applied by the compiler.
    pub negated: bool,

    /// The database backend (PostgreSQL, MySQL, SQLite).
    /// Used for backend-specific SQL generation.
    pub backend: Backend,

    /// For JSON key transforms (e.g., bio__key__priority), this holds the key name ("priority")
    /// Used by apply_transform() to generate correct JSON path accessors.
    pub json_key: Option<String>,
}

/// The function signature for a built-in lookup implementation.
///
/// Takes a `LookupContext` and returns a SQL fragment string.
/// The function must be `fn` (not closure) to be `Send + Sync`.
pub type LookupFn = fn(&LookupContext) -> String;

/// A lookup that was registered from Python: stores the callable and a
/// Rust-generated SQL template where `{col}` is the column placeholder.
///
/// Python-registered lookups are called at SQL-build time with the column
/// name substituted in. This avoids holding the GIL for every query.
/// The Python callable is only invoked once at registration time to extract
/// the SQL template string.
#[derive(Debug, Clone)]
pub struct PythonLookup {
    /// Pre-rendered SQL template. Example: `"LOWER({col}) LIKE LOWER(?)"`
    /// The caller substitutes `{col}` with the actual column name.
    pub sql_template: String,
}

//
// Global lookup registry
//
/// The two registries live side-by-side:
/// - `builtin`: populated once at startup with the built-in lookups
/// - `custom`:  populated at runtime with user-registered lookups
///
/// We check `custom` first so users can override built-ins (e.g., to change
/// the SQL generated by `icontains` for a database that has native ILIKE).
struct LookupRegistry {
    builtin: HashMap<&'static str, LookupFn>,
    custom: HashMap<String, PythonLookup>,
}

static REGISTRY: OnceLock<RwLock<LookupRegistry>> = OnceLock::new();

/// Initialize the registry with all built-in lookups.
/// Called once from `lib.rs` module initialization.
pub fn init_registry() {
    REGISTRY.get_or_init(|| {
        let mut builtin = HashMap::new();

        // Comparison lookups
        builtin.insert("exact", exact as LookupFn);
        builtin.insert("gt", gt as LookupFn);
        builtin.insert("gte", gte as LookupFn);
        builtin.insert("lt", lt as LookupFn);
        builtin.insert("lte", lte as LookupFn);

        // String lookups
        builtin.insert("contains", contains as LookupFn);
        builtin.insert("icontains", icontains as LookupFn);
        builtin.insert("startswith", startswith as LookupFn);
        builtin.insert("istartswith", istartswith as LookupFn);
        builtin.insert("endswith", endswith as LookupFn);
        builtin.insert("iendswith", iendswith as LookupFn);

        // Null lookups
        // `isnull` is special: it ignores the value entirely and produces
        // IS NULL / IS NOT NULL. The value passed (True/False) is read by
        // the compiler, not by this function.
        builtin.insert("isnull", isnull as LookupFn);

        // Membership lookups
        // `in` is also special: the compiler expands it into
        // `col IN (?, ?, ?)` based on the number of values provided.
        builtin.insert("in", in_lookup as LookupFn);

        // Range lookup
        builtin.insert("range", range as LookupFn);

        // Date/Time transforms (for chaining like created_at__date__gte)
        // These are registered as lookups that return SQL fragments
        builtin.insert("date", date_transform as LookupFn);
        builtin.insert("year", year_transform as LookupFn);
        builtin.insert("month", month_transform as LookupFn);
        builtin.insert("day", day_transform as LookupFn);
        builtin.insert("hour", hour_transform as LookupFn);
        builtin.insert("minute", minute_transform as LookupFn);
        builtin.insert("second", second_transform as LookupFn);
        builtin.insert("week", week_transform as LookupFn);
        builtin.insert("dow", dow_transform as LookupFn);
        // New transforms
        builtin.insert("quarter", quarter_transform as LookupFn);
        builtin.insert("time", time_transform as LookupFn);
        builtin.insert("iso_week", iso_week_transform as LookupFn);
        builtin.insert("iso_dow", iso_dow_transform as LookupFn);

        // JSON transforms (for chaining like metadata__key__icontains)
        builtin.insert("key", json_key_transform as LookupFn);
        builtin.insert("key_text", json_key_text_transform as LookupFn);
        builtin.insert("json", json_cast_transform as LookupFn);

        // JSON lookups (comparison operators)
        builtin.insert("has_key", json_has_key as LookupFn);
        builtin.insert("has_keys", json_has_keys as LookupFn);
        builtin.insert("contains", json_contains as LookupFn);
        builtin.insert("contained_by", json_contained_by as LookupFn);

        RwLock::new(LookupRegistry {
            builtin,
            custom: HashMap::new(),
        })
    });
}

//
// Registry public API
//
/// Register a custom lookup from Python.
///
/// # Arguments
/// * `name`         — the lookup name (e.g. `"uuid_prefix"`)
/// * `sql_template` — SQL fragment with `{col}` as column placeholder and
///                    `?` as value placeholder. Example: `"{col}::text LIKE ?"`
///
/// # Errors
/// Returns `RyxError::Internal` if the registry hasn't been initialized
/// (should never happen in practice since `init_registry()` runs at import).
pub fn register_custom(name: impl Into<String>, sql_template: impl Into<String>) -> RyxResult<()> {
    let registry = REGISTRY
        .get()
        .ok_or_else(|| RyxError::Internal("Lookup registry not initialized".into()))?;

    let mut guard = registry
        .write()
        .map_err(|e| RyxError::Internal(format!("Registry lock poisoned: {e}")))?;

    guard.custom.insert(
        name.into(),
        PythonLookup {
            sql_template: sql_template.into(),
        },
    );

    Ok(())
}

// ###
// Chained lookups support (e.g., "date__gte", "year__month")
// ###

/// Handle SQLite transform lookup when ctx.column already has transform applied
/// This happens when compiler applied the transform but lookup is still simple (e.g., "gte")
#[allow(dead_code)]
fn handle_sqlite_transform_lookup(
    field: &str,
    _transform: &str,
    lookup_name: &str,
    ctx: &LookupContext,
) -> RyxResult<String> {
    // Check if we need to convert TEXT to INTEGER for numeric comparisons
    let is_numeric_comparison = matches!(lookup_name, "gt" | "gte" | "lt" | "lte" | "exact");

    if is_numeric_comparison && ctx.column.contains("AS TEXT)") {
        // Convert TEXT to INTEGER
        let transformed = ctx.column.replace("AS TEXT)", "AS INTEGER)");
        let new_ctx = LookupContext {
            column: transformed,
            negated: ctx.negated,
            backend: ctx.backend,
            json_key: ctx.json_key.clone(),
        };
        return resolve_simple(field, lookup_name, &new_ctx);
    }

    // Otherwise, use as-is
    resolve_simple(field, lookup_name, ctx)
}

/// Resolve a chained lookup like "date__gte" or "year__exact".
/// This applies transforms first (date, year, month, etc.) then the final lookup.
pub fn resolve(field: &str, lookup_name: &str, ctx: &LookupContext) -> RyxResult<String> {
    // If no "__", it's a simple lookup
    if !lookup_name.contains("__") {
        // Check if we have a JSON key that needs to be applied
        if ctx.json_key.is_some() {
            // We have a JSON key transform to apply - ALWAYS start fresh from field
            let mut column = format!("\"{}\"", field);
            // Apply the key transform with the json_key
            column = apply_transform("key", &column, ctx.backend, ctx.json_key.as_deref())?;

            // Build new context with transformed column
            let json_ctx = LookupContext {
                column: column.clone(),
                negated: ctx.negated,
                backend: ctx.backend,
                json_key: None,
            };
            return resolve_simple(field, lookup_name, &json_ctx);
        }

        // Check if ctx.column already has a date/time transform applied (e.g., from compiler)
        // Handle the case where compiler applied transform but lookup is simple (e.g., "gte")
        if ctx.column.contains("strftime") || ctx.column.contains("DATE(") {
            // Detect transform type from SQL
            if ctx.column.contains("strftime('%Y'") {
                return handle_sqlite_transform_lookup(field, "year", lookup_name, ctx);
            } else if ctx.column.contains("strftime('%m'") {
                return handle_sqlite_transform_lookup(field, "month", lookup_name, ctx);
            } else if ctx.column.contains("strftime('%d'") {
                return handle_sqlite_transform_lookup(field, "day", lookup_name, ctx);
            } else if ctx.column.contains("strftime('%H'") {
                return handle_sqlite_transform_lookup(field, "hour", lookup_name, ctx);
            }
            // For DATE() transform, we need different handling for comparisons
            if ctx.column.starts_with("DATE(") {
                return resolve_simple(field, lookup_name, ctx);
            }
        }
        return resolve_simple(field, lookup_name, ctx);
    }

    // Chained: split into transforms + final lookup
    let parts: Vec<&str> = lookup_name.split("__").collect();
    let final_lookup = *parts.last().unwrap();
    let transform_parts: Vec<&str> = parts[..parts.len() - 1].to_vec();

    // Start fresh from the base column - don't use ctx.column which may already have transforms
    let mut column = format!("\"{}\"", field);

    // Apply transforms in order until we hit a lookup
    // For JSON transforms like "key", use ctx.json_key if available
    for transform in transform_parts.iter() {
        // Check if this is a known transform
        let is_transform = matches!(
            *transform,
            "date"
                | "year"
                | "month"
                | "day"
                | "hour"
                | "minute"
                | "second"
                | "week"
                | "dow"
                | "quarter"
                | "time"
                | "iso_week"
                | "iso_dow"
                | "key"
                | "key_text"
                | "json"
        );

        if is_transform {
            // For JSON transforms (key, key_text), use json_key from context if available
            let key = if matches!(*transform, "key" | "key_text") {
                ctx.json_key
                    .as_deref()
                    .or_else(|| field.rsplit("__").next())
            } else {
                None
            };
            column = apply_transform(transform, &column, ctx.backend, key)?;
        } else {
            // This part is a lookup, not a transform - stop here
            break;
        }
    }

    // Build a new context with the transformed column
    let final_ctx = LookupContext {
        column: column.clone(),
        negated: ctx.negated,
        backend: ctx.backend,
        json_key: ctx.json_key.clone(),
    };

    // For SQLite, handle type conversion for comparisons on transformed values
    if ctx.backend == Backend::SQLite {
        // Check if the column contains a date/time transform
        let col_has_transform = column.contains("strftime");

        if col_has_transform && !column.contains("AS INTEGER") {
            // Column is TEXT from a transform, need to convert for numeric comparisons
            let is_numeric_comparison =
                matches!(final_lookup, "gt" | "gte" | "lt" | "lte" | "exact");

            if is_numeric_comparison {
                // Convert TEXT to INTEGER by replacing AS TEXT with AS INTEGER
                let transformed = column.replace("AS TEXT)", "AS INTEGER)");
                let final_ctx_int = LookupContext {
                    column: transformed,
                    negated: ctx.negated,
                    backend: ctx.backend,
                    json_key: ctx.json_key.clone(),
                };
                return resolve_simple(field, final_lookup, &final_ctx_int);
            }

            // For non-numeric comparisons, cast the bind value
            let fragment = resolve_simple(field, final_lookup, &final_ctx)?;
            return Ok(add_sqlite_cast_for_transform(&fragment, final_lookup));
        }
    }

    // Default: resolve normally
    resolve_simple(field, final_lookup, &final_ctx)
}

#[allow(dead_code)]
/// Convert a SQLite transform expression from TEXT to INTEGER for numeric comparisons
fn convert_transform_to_integer(column: &str) -> String {
    // Replace CAST(...AS TEXT) with CAST(...AS INTEGER)
    column.replace("AS TEXT)", "AS INTEGER)")
}

/// Add CAST(? AS TEXT) for SQLite date/time transform comparisons
fn add_sqlite_cast_for_transform(fragment: &str, lookup: &str) -> String {
    // For lookups that use = ?, replace = ? with = CAST(? AS TEXT)
    // For lookups that use > ?, etc., replace with > CAST(? AS TEXT)

    match lookup {
        "exact" => fragment.replace("= ?", "= CAST(? AS TEXT)"),
        "gt" => fragment.replace("> ?", "> CAST(? AS TEXT)"),
        "gte" => fragment.replace(">= ?", ">= CAST(? AS TEXT)"),
        "lt" => fragment.replace("< ?", "< CAST(? AS TEXT)"),
        "lte" => fragment.replace("<= ?", "<= CAST(? AS TEXT)"),
        _ => fragment.to_string(),
    }
}

/// Resolve a simple (non-chained) lookup.
fn resolve_simple(field: &str, lookup_name: &str, ctx: &LookupContext) -> RyxResult<String> {
    let registry = REGISTRY
        .get()
        .ok_or_else(|| RyxError::Internal("Lookup registry not initialized".into()))?;

    let guard = registry
        .read()
        .map_err(|e| RyxError::Internal(format!("Registry lock poisoned: {e}")))?;

    // Check custom registry first (allows overriding built-ins)
    if let Some(custom) = guard.custom.get(lookup_name) {
        return Ok(custom.sql_template.replace("{col}", &ctx.column));
    }

    // Fall back to built-in lookup functions
    if let Some(lookup_fn) = guard.builtin.get(lookup_name) {
        return Ok(lookup_fn(ctx));
    }

    Err(RyxError::UnknownLookup {
        field: field.to_string(),
        lookup: lookup_name.to_string(),
    })
}

/// Returns the list of all registered lookup names (built-in + custom).
/// Used by the Python layer to provide helpful error messages and IDE
/// autocompletion support.
pub fn registered_lookups() -> RyxResult<Vec<String>> {
    let registry = REGISTRY
        .get()
        .ok_or_else(|| RyxError::Internal("Lookup registry not initialized".into()))?;

    let guard = registry
        .read()
        .map_err(|e| RyxError::Internal(format!("Registry lock poisoned: {e}")))?;

    let mut names: Vec<String> = guard
        .builtin
        .keys()
        .map(|k| k.to_string())
        .chain(guard.custom.keys().cloned())
        .collect();
    names.sort();
    Ok(names)
}

/// Apply a field transformation (date, year, month, key, etc.)
/// Returns SQL like "DATE(col)" or "EXTRACT(YEAR FROM col)"
/// For JSON transforms (key, key_text), the key is extracted from the next part of the chain
pub fn apply_transform(
    name: &str,
    column: &str,
    backend: Backend,
    key: Option<&str>,
) -> RyxResult<String> {
    let sql = match (name, backend) {
        // Date/Time transforms
        ("date", _) => format!("DATE({})", column),

        ("year", Backend::PostgreSQL) => format!("EXTRACT(YEAR FROM {})", column),
        ("year", Backend::MySQL) => format!("YEAR({})", column),
        ("year", Backend::SQLite) => format!("CAST(strftime('%Y', {}) AS TEXT)", column),

        ("month", Backend::PostgreSQL) => format!("EXTRACT(MONTH FROM {})", column),
        ("month", Backend::MySQL) => format!("MONTH({})", column),
        ("month", Backend::SQLite) => format!("CAST(strftime('%m', {}) AS TEXT)", column),

        ("day", Backend::PostgreSQL) => format!("EXTRACT(DAY FROM {})", column),
        ("day", Backend::MySQL) => format!("DAYOFMONTH({})", column),
        ("day", Backend::SQLite) => format!("CAST(strftime('%d', {}) AS TEXT)", column),

        ("hour", Backend::PostgreSQL) => format!("EXTRACT(HOUR FROM {})", column),
        ("hour", Backend::MySQL) => format!("HOUR({})", column),
        ("hour", Backend::SQLite) => format!("CAST(strftime('%H', {}) AS TEXT)", column),

        ("minute", Backend::PostgreSQL) => format!("EXTRACT(MINUTE FROM {})", column),
        ("minute", Backend::MySQL) => format!("MINUTE({})", column),
        ("minute", Backend::SQLite) => format!("CAST(strftime('%M', {}) AS TEXT)", column),

        ("second", Backend::PostgreSQL) => format!("EXTRACT(SECOND FROM {})", column),
        ("second", Backend::MySQL) => format!("SECOND({})", column),
        ("second", Backend::SQLite) => format!("CAST(strftime('%S', {}) AS TEXT)", column),

        ("week", Backend::PostgreSQL) => format!("EXTRACT(WEEK FROM {})", column),
        ("week", Backend::MySQL) => format!("WEEK({})", column),
        ("week", Backend::SQLite) => format!("CAST(strftime('%W', {}) AS TEXT)", column),

        ("dow", Backend::PostgreSQL) => format!("EXTRACT(DOW FROM {})", column),
        ("dow", Backend::MySQL) => format!("DAYOFWEEK({})", column),
        ("dow", Backend::SQLite) => format!("CAST(strftime('%w', {}) AS TEXT)", column),

        // New Date/Time transforms
        ("quarter", Backend::PostgreSQL) => format!("EXTRACT(QUARTER FROM {})", column),
        ("quarter", Backend::MySQL) => format!("QUARTER({})", column),
        ("quarter", Backend::SQLite) => format!(
            "CAST((CAST(strftime('%m', {}) AS INTEGER) + 2) / 3 AS TEXT)",
            column
        ),

        ("time", Backend::PostgreSQL) => format!("TIME({})", column),
        ("time", Backend::MySQL) => format!("TIME({})", column),
        ("time", Backend::SQLite) => format!("time({})", column),

        ("iso_week", Backend::PostgreSQL) => format!("EXTRACT(ISOWEEK FROM {})", column),
        ("iso_week", Backend::MySQL) => format!(
            "WEEK({}, 1) - WEEK(DATE_SUB({}, INTERVAL (DAYOFWEEK({}) - 1) DAY), 0) + 1",
            column, column, column
        ),
        ("iso_week", Backend::SQLite) => format!("CAST(strftime('%W', {}) AS TEXT)", column),

        ("iso_dow", Backend::PostgreSQL) => format!("EXTRACT(ISODOW FROM {})", column),
        ("iso_dow", Backend::MySQL) => format!("((DAYOFWEEK({}) + 5) % 7) + 1", column),
        ("iso_dow", Backend::SQLite) => format!("CAST(strftime('%w', {}) AS TEXT)", column),

        // JSON transforms (key extraction) - key comes from the next part of the chain
        ("key", Backend::PostgreSQL) => {
            let k = key.unwrap_or("key");
            format!("({}->>'{}')", column, k)
        }
        ("key", Backend::MySQL) => {
            let k = key.unwrap_or("key");
            format!("JSON_UNQUOTE(JSON_EXTRACT({}, '$.{}'))", column, k)
        }
        ("key", Backend::SQLite) => {
            let k = key.unwrap_or("key");
            format!("json_extract({}, '$.{}')", column, k)
        }

        ("key_text", Backend::PostgreSQL) => {
            let k = key.unwrap_or("key");
            format!("({}->>'{}')::text", column, k)
        }
        ("key_text", Backend::MySQL) => {
            let k = key.unwrap_or("key");
            format!(
                "CAST(JSON_UNQUOTE(JSON_EXTRACT({}, '.{}')) AS CHAR)",
                column, k
            )
        }
        ("key_text", Backend::SQLite) => {
            let k = key.unwrap_or("key");
            format!("CAST(json_extract({}, '.{}') AS TEXT)", column, k)
        }

        ("json", Backend::PostgreSQL) => format!("({}::jsonb)", column),
        ("json", Backend::MySQL) => column.to_string(),
        ("json", Backend::SQLite) => column.to_string(),

        _ => {
            return Err(RyxError::UnknownLookup {
                field: column.to_string(),
                lookup: name.to_string(),
            })
        }
    };

    Ok(sql)
}

// ###
// Built-in lookup implementations
//
// Each function takes a `LookupContext` and returns a SQL fragment.
// Rules:
//   - Always use `?` as the value placeholder
//   - Never include the value itself (SQL injection prevention)
//   - Column name is already safely quoted by the query builder
// ###

/// `field__exact=value` → `field = ?`
///
/// This is also the *implicit* lookup: `filter(name="Alice")` is equivalent
/// to `filter(name__exact="Alice")`.
fn exact(ctx: &LookupContext) -> String {
    format!("{} = ?", ctx.column)
}

/// `field__gt=value` → `field > ?`
fn gt(ctx: &LookupContext) -> String {
    format!("{} > ?", ctx.column)
}

/// `field__gte=value` → `field >= ?`
fn gte(ctx: &LookupContext) -> String {
    format!("{} >= ?", ctx.column)
}

/// `field__lt=value` → `field < ?`
fn lt(ctx: &LookupContext) -> String {
    format!("{} < ?", ctx.column)
}

/// `field__lte=value` → `field <= ?`
fn lte(ctx: &LookupContext) -> String {
    format!("{} <= ?", ctx.column)
}

/// `field__contains="bob"` → `field LIKE ?`  (with `%value%` at bind time)
///
/// Case-sensitive substring match. The `%` wrapping is applied by the
/// executor when binding the value, not in the SQL fragment itself.
fn contains(ctx: &LookupContext) -> String {
    format!("{} LIKE ?", ctx.column)
}

/// `field__icontains="bob"` → `LOWER(field) LIKE LOWER(?)`
///
/// Case-insensitive substring match. Works on all backends without relying
/// on PostgreSQL-specific `ILIKE`. The `%value%` wrapping happens at bind time.
fn icontains(ctx: &LookupContext) -> String {
    format!("LOWER({}) LIKE LOWER(?)", ctx.column)
}

/// `field__startswith="pr"` → `field LIKE ?`  (with `value%` at bind time)
fn startswith(ctx: &LookupContext) -> String {
    format!("{} LIKE ?", ctx.column)
}

/// `field__istartswith="pr"` → `LOWER(field) LIKE LOWER(?)`
fn istartswith(ctx: &LookupContext) -> String {
    format!("LOWER({}) LIKE LOWER(?)", ctx.column)
}

/// `field__endswith="ing"` → `field LIKE ?`  (with `%value` at bind time)
fn endswith(ctx: &LookupContext) -> String {
    format!("{} LIKE ?", ctx.column)
}

/// `field__iendswith="ing"` → `LOWER(field) LIKE LOWER(?)`
fn iendswith(ctx: &LookupContext) -> String {
    format!("LOWER({}) LIKE LOWER(?)", ctx.column)
}

/// `field__isnull=True` → `field IS NULL`
/// `field__isnull=False` → `field IS NOT NULL`
///
/// Note: the True/False distinction is handled by the compiler which reads the
/// bound value. This function always returns the IS NULL form; the compiler
/// swaps to IS NOT NULL when the value is False/0.
fn isnull(ctx: &LookupContext) -> String {
    // The compiler reads the Python boolean and rewrites this.
    // We return the base form here.
    format!("{} IS NULL", ctx.column)
}

/// `field__in=[1, 2, 3]` → `field IN (?, ?, ?)`
///
/// Note: this returns a *template* — the compiler replaces `(?)` with
/// the correct number of placeholders based on the list length.
fn in_lookup(ctx: &LookupContext) -> String {
    // Single `?` — compiler expands to `(?, ?, ...)` based on value count
    format!("{} IN (?)", ctx.column)
}

/// `field__range=(low, high)` → `field BETWEEN ? AND ?`
///
/// Uses two bind parameters. The compiler handles this specially.
fn range(ctx: &LookupContext) -> String {
    format!("{} BETWEEN ? AND ?", ctx.column)
}

// ###
// Date/Time Transform Functions (for chained lookups)
// ###

/// `field__date` → `DATE(field)` (backend-aware) - implicit equality
pub fn date_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("DATE({}) = ?", ctx.column),
        Backend::MySQL => format!("DATE({}) = ?", ctx.column),
        Backend::SQLite => format!("date({}) = CAST(? AS TEXT)", ctx.column),
    }
}

/// `field__year` → `EXTRACT(YEAR FROM field)` or `YEAR(field)` (backend-aware) - implicit equality
pub fn year_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(YEAR FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("YEAR({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%Y', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__month` → `EXTRACT(MONTH FROM field)` or `MONTH(field)` (backend-aware) - implicit equality
pub fn month_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(MONTH FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("MONTH({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%m', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__day` → `EXTRACT(DAY FROM field)` or `DAY(field)` (backend-aware) - implicit equality
pub fn day_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(DAY FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("DAYOFMONTH({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%d', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__hour` → `EXTRACT(HOUR FROM field)` or `HOUR(field)` (backend-aware) - implicit equality
pub fn hour_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(HOUR FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("HOUR({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%H', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__minute` → `EXTRACT(MINUTE FROM field)` or `MINUTE(field)` (backend-aware) - implicit equality
pub fn minute_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(MINUTE FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("MINUTE({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%M', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__second` → `EXTRACT(SECOND FROM field)` or `SECOND(field)` (backend-aware) - implicit equality
pub fn second_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(SECOND FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("SECOND({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%S', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__week` → `EXTRACT(WEEK FROM field)` or `WEEK(field)` (backend-aware) - implicit equality
pub fn week_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(WEEK FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("WEEK({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%W', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__dow` → `EXTRACT(DOW FROM field)` or `DAYOFWEEK(field)` (backend-aware) - implicit equality
pub fn dow_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(DOW FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("DAYOFWEEK({}) = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%w', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__quarter` → `EXTRACT(QUARTER FROM field)` or `QUARTER(field)` (backend-aware) - implicit equality
pub fn quarter_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(QUARTER FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("QUARTER({}) = ?", ctx.column),
        Backend::SQLite => format!(
            "((CAST(strftime('%m', {}) AS INTEGER) + 2) / 3) = ?",
            ctx.column
        ),
    }
}

/// `field__time` → `TIME(field)` or equivalent (backend-aware) - implicit equality
pub fn time_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("TIME({}) = ?", ctx.column),
        Backend::MySQL => format!("TIME({}) = ?", ctx.column),
        Backend::SQLite => format!("time({}) = ?", ctx.column),
    }
}

/// `field__iso_week` → `EXTRACT(ISOWEEK FROM field)` or equivalent (backend-aware) - implicit equality
pub fn iso_week_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(ISOWEEK FROM {}) = ?", ctx.column),
        Backend::MySQL => format!(
            "WEEK({}, 1) - WEEK(DATE_SUB({}, INTERVAL (DAYOFWEEK({}) - 1) DAY), 0) + 1 = ?",
            ctx.column, ctx.column, ctx.column
        ),
        Backend::SQLite => format!("CAST(strftime('%W', {}) AS INTEGER) = ?", ctx.column),
    }
}

/// `field__iso_dow` → `EXTRACT(ISODOW FROM field)` or equivalent (backend-aware) - implicit equality
pub fn iso_dow_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("EXTRACT(ISODOW FROM {}) = ?", ctx.column),
        Backend::MySQL => format!("((DAYOFWEEK({}) + 5) % 7) + 1 = ?", ctx.column),
        Backend::SQLite => format!("CAST(strftime('%w', {}) AS INTEGER) = ?", ctx.column),
    }
}

// ###
// JSON Transform Functions (for chained lookups)
// ###

/// `field__key` → `(field->>'key')` or `JSON_UNQUOTE(JSON_EXTRACT(field, '$.key'))`
pub fn json_key_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("({}->>'key')", ctx.column),
        Backend::MySQL => format!("JSON_UNQUOTE(JSON_EXTRACT({}, '$.key'))", ctx.column),
        Backend::SQLite => format!("json_extract({}, '$.key')", ctx.column),
    }
}

/// `field__key_text` → `(field->>'key')::text` (for text comparisons like icontains)
pub fn json_key_text_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("({}->>'key')::text", ctx.column),
        Backend::MySQL => format!(
            "CAST(JSON_UNQUOTE(JSON_EXTRACT({}, '$.key')) AS CHAR)",
            ctx.column
        ),
        Backend::SQLite => format!("CAST(json_extract({}, '$.key') AS TEXT)", ctx.column),
    }
}

/// `field__json` → `field::jsonb` (PostgreSQL) or just field (MySQL/SQLite)
pub fn json_cast_transform(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("({}::jsonb)", ctx.column),
        Backend::MySQL => ctx.column.clone(),
        Backend::SQLite => ctx.column.clone(),
    }
}

// ###
// JSON Lookup Functions (comparison operators)
// ###

/// `field__has_key="key"` → `field ? 'key'` (PostgreSQL) or `JSON_CONTAINS(field, '"key"')` (MySQL)
fn json_has_key(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("({} ? 'key')", ctx.column),
        Backend::MySQL => format!("JSON_CONTAINS({}, '\"key\"')", ctx.column),
        Backend::SQLite => format!("json_extract({}, '$.key') IS NOT NULL", ctx.column),
    }
}

/// `field__has_keys=['key1', 'key2']` → `field ?& array['key1', 'key2']`
fn json_has_keys(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("({} ?& array['key1', 'key2'])", ctx.column),
        Backend::MySQL => format!("JSON_CONTAINS({}, '[\"key1\", \"key2\"]')", ctx.column),
        Backend::SQLite => format!(
            "json_extract({}, '$.key1') IS NOT NULL AND json_extract({}, '$.key2') IS NOT NULL",
            ctx.column, ctx.column
        ),
    }
}

/// `field__contains={"key": "value"}` → `field @> ?` (PostgreSQL)
fn json_contains(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("({} @> ?)", ctx.column),
        Backend::MySQL => format!("JSON_CONTAINS({}, ?)", ctx.column),
        Backend::SQLite => ctx.column.clone(), // Limited support in SQLite
    }
}

/// `field__contained_by={"key": "value"}` → `field <@ ?` (PostgreSQL)
fn json_contained_by(ctx: &LookupContext) -> String {
    match ctx.backend {
        Backend::PostgreSQL => format!("({} <@ ?)", ctx.column),
        Backend::MySQL => format!("JSON_CONTAINS(?, {})", ctx.column),
        Backend::SQLite => ctx.column.clone(), // Limited support in SQLite
    }
}
