from __future__ import annotations

import argparse
import sys

from ryx.cli.commands.base import Command
from ryx.cli.config import get_config


class InspectDbCommand(Command):
    """Introspect the database and print model class stubs."""

    name = "inspectdb"
    help = "Introspect database and print model stubs"
    description = (
        "Introspect an existing database and generate ryx Model class stubs. "
        "This is useful for reverse engineering models from an existing database."
    )

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "--table", metavar="TABLE", help="Introspect only this table"
        )
        parser.add_argument(
            "--output",
            "-o",
            metavar="FILE",
            help="Write output to file instead of stdout",
        )

    async def execute(self, args: argparse.Namespace) -> int:
        config = get_config()
        url = self._resolve_url(args, config)

        if not url:
            self._print_missing_url()
            return 1

        import ryx

        await ryx.setup(url)

        from ryx.executor_helpers import raw_fetch

        # Get table list (Postgres / MySQL)
        try:
            tables = await raw_fetch(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_type = 'BASE TABLE'"
            )
        except Exception:
            tables = await raw_fetch(
                "SELECT name AS table_name FROM sqlite_master WHERE type='table'"
            )

        target_table = getattr(args, "table", None)

        output = []
        output.append("# Generated by `python -m ryx inspectdb`\n")
        output.append(
            "from ryx import Model, CharField, IntField, BooleanField, TextField\n"
        )
        output.append("from ryx import DateTimeField, FloatField, DecimalField\n\n")

        for row in tables:
            table_name = row.get("table_name") or row.get("name", "")
            if not table_name or table_name.startswith("ryx_"):
                continue
            if target_table and table_name != target_table:
                continue

            # Fetch columns
            try:
                cols = await raw_fetch(
                    f"SELECT column_name, data_type, is_nullable, column_default "
                    f"FROM information_schema.columns WHERE table_name = '{table_name}' "
                    f"ORDER BY ordinal_position"
                )
            except Exception:
                cols = await raw_fetch(f'PRAGMA table_info("{table_name}")')

            class_name = self._snake_to_pascal(table_name)
            output.append(f"class {class_name}(Model):")
            output.append("    class Meta:")
            output.append(f"        table_name = {table_name!r}\n")

            for col in cols:
                col_name = col.get("column_name") or col.get("name", "unknown")
                col_type = (col.get("data_type") or col.get("type") or "TEXT").upper()
                nullable = col.get("is_nullable", "YES") == "YES" or bool(
                    col.get("notnull", 0) == 0
                )
                field_type = self._db_type_to_field(col_type)
                null_kw = ", null=True" if nullable else ""
                output.append(f"    {col_name} = {field_type}({null_kw})")

            output.append("")

        output_str = "\n".join(output)

        # Output to file or stdout
        if getattr(args, "output", None):
            with open(args.output, "w") as f:
                f.write(output_str)
            print(f"[ryx] Models written to {args.output}")
        else:
            print(output_str)

        return 0

    def _resolve_url(self, args, config) -> str:
        url = getattr(args, "url", None)
        if url:
            return url
        return config.resolve_url()

    def _print_missing_url(self) -> None:
        print(
            "[ryx] No database URL found.\n"
            "  Set RYX_DATABASE_URL environment variable, or\n"
            "  pass --url postgres://user:pass@host/db"
        )

    def _snake_to_pascal(self, name: str) -> str:
        return "".join(w.capitalize() for w in name.split("_"))

    def _db_type_to_field(self, db_type: str) -> str:
        dt = db_type.upper()
        if "INT" in dt:
            return "IntField"
        if "FLOAT" in dt or "REAL" in dt or "DOUBLE" in dt:
            return "FloatField"
        if "NUMERIC" in dt or "DECIMAL" in dt:
            return "DecimalField"
        if "BOOL" in dt:
            return "BooleanField"
        if "TEXT" in dt:
            return "TextField"
        if "TIMESTAMP" in dt or "DATETIME" in dt:
            return "DateTimeField"
        return "CharField(max_length=255)"


# Legacy function for backward compatibility
async def cmd_inspectdb(args) -> None:
    cmd = InspectDbCommand()
    await cmd.execute(args)
